spring:
  datasource:
    username: 你的用户名
    password: 你的密码
    url: jdbc:mysql://localhost:3306/ourblog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations: com.cy.springbootshironodb.mapper/*Mapper.xml
  type-aliases-package: com.cy.springbootshironodb.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : info
# 文件上传

