spring:

  aop:
    proxy-target-class: true
    expose-proxy: true



#showSql
logging:
  level:
    com:
      example:
        mapper : info
# 文件上传
Resources:
  FunctionName:
    Properties:
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: local

